"use server";

import { getAppointmentByToken, updateAppointmentStatus } from "@/lib/data/appointments";
import { isPastDate } from "@/lib/booking/date-utils";
import { getClientIp } from "@/lib/security/client-ip";
import { checkRateLimit } from "@/lib/security/rate-limit";
import { recordAppointmentEvent } from "@/lib/data/audit";

export type CancelActionState = {
  status: "idle" | "success" | "error";
  message?: string;
};

const GENERIC_BLOCKED_MESSAGE = "We couldn't process that request. Please try again in a few minutes.";

/**
 * Looking up and updating by token both go through the service-role
 * client (inside lib/data/appointments.ts) rather than RLS, because
 * there's no anon policy that could express this safely: RLS policies
 * grant access based on the ROLE making the request, not on "does this
 * particular request happen to know a specific token value." That's a
 * job for application logic — this function IS the check. It looks up
 * the one row matching the token, confirms it's actually cancellable,
 * and only then updates it. Nothing about that flow should be reachable
 * any other way, which is also why there's deliberately no
 * "list appointments" admin view anywhere in this app yet — that's
 * square in the scope of the phase-3 security pass, not this one.
 *
 * The token itself is a UUID v4 (~122 bits of entropy) generated by
 * Postgres and only ever handed out once, in the confirmation email —
 * guessing a valid one by brute force isn't a realistic attack, so this
 * function doesn't add expiry or extra secrecy around the token for that
 * reason. The rate limit below exists anyway, for the same generic
 * endpoint-hammering hygiene every action here gets, not because token
 * guessing is the threat it's stopping.
 */
export async function cancelAppointment(
  _prevState: CancelActionState,
  formData: FormData,
): Promise<CancelActionState> {
  const ip = await getClientIp();

  const rateLimit = await checkRateLimit(ip, { action: "cancellation", maxAttempts: 10, windowMinutes: 15 });
  if (!rateLimit.allowed) {
    return { status: "error", message: GENERIC_BLOCKED_MESSAGE };
  }

  try {
    const token = formData.get("token");
    if (typeof token !== "string" || token.length === 0) {
      return { status: "error", message: "Missing cancellation link." };
    }

    const appointment = await getAppointmentByToken(token);
    if (!appointment) {
      return { status: "error", message: "We couldn't find that appointment." };
    }
    if (appointment.status === "cancelled") {
      return { status: "success", message: "This appointment is already cancelled." };
    }
    if (appointment.status === "completed") {
      return { status: "error", message: "This appointment already happened and can't be cancelled." };
    }
    // A confirmed appointment whose date has already gone by shouldn't be
    // cancellable at all — it's not a live booking anymore (it just never
    // got marked "completed"), and letting a stale token still change its
    // status is a needless window left open with no upside for anyone.
    if (isPastDate(appointment.date)) {
      return { status: "error", message: "This appointment already happened and can't be cancelled." };
    }

    await updateAppointmentStatus(token, "cancelled");

    // Best-effort, same reasoning as the audit write in submitBooking —
    // the status update above already succeeded, so a logging failure
    // here must not be reported back as the cancellation having failed.
    try {
      await recordAppointmentEvent(appointment.id, "cancelled", ip);
    } catch (err) {
      console.error("Failed to record appointment cancellation event:", err);
    }

    return { status: "success", message: "Your appointment has been cancelled." };
  } catch (err) {
    // See the matching catch in lib/actions/booking.ts: keeps a thrown DB
    // error from breaking out of the Server Action's expected return
    // shape and surfacing raw detail to the browser instead of this
    // page's own generic message.
    console.error("Unexpected error in cancelAppointment:", err);
    return { status: "error", message: "Something went wrong. Please try again." };
  }
}
